site_name: ChainXim Documentation

theme:
  name: material
  language: zh
  features:
    - content.math

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          link: /chainxim-documentation/en/
        - locale: zh
          name: 简体中文
          default: true
          build: true
          link: /chainxim-documentation/

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  

